baseURL = 'http://marceloexc.com'
languageCode = 'en-us'
title = 'marceloexc.com'
theme = "marceloexc-theme"
contentDir = "content/"


enableGitInfo = true

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[menu]
[[menu.main]]
  pageRef = '/about'
  weight = 20
[[menu.main]]
  name = 'Gallery'
  pageRef = '/gallery'
  weight = 30
[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 35
[[menu.main]]
	name = 'Music'
	pageRef = '/music'
	weight = 40
  [[menu.main]]
	name = 'Links'
	pageRef = '/links'
	weight = 50
  [[menu.main]]
  name = 'Museum'
  
  weight = 60
  



